### ISSUE TITLE
Setup ip issue/question

### ISSUE THREAD

**Issue by aabhutta** [Torrentus/UnifiProtectCrx#3]
Newbi setting it up 
Not sure where to access the following ‘IP-address of your Unifi Protect installation’
Is there a specific Ip for my unifi protect installation on cloud key Gen 2 plus.
I have the ip that displays ok the front panel of cloud key but is this the same ip that will go into the file you have mentioned. Thanks!

**Comment by remcotjeerdsma** [comment]
Hi, sorry for the late reply. 

See this part of the documentation:

_In live-view.html, change the src of the webview to the IP-address of your Unifi Protect installation. 
This is tested with the non-encrypted 7080 port, please use that if possible (for performance and to avoid certificate acceptence issues for self-signed certificates).
Leave the '/login?redirect=%2Fliveview' part of the URL untouched._

The IP-adress that you need is indeed the ip-adress that you see on the CKG2 front panel or the cloud key's web UI. The port (7080) makes that it is directed at the Unifi Protect/video part of the CKG2 and not the management console or network service.
